blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from blog import views

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name="index"),

    url(r'^post/(?P<pk>[0-9]+)$', views.BlogDetail.as_view(), name="post"),
    url(r'^post/(?P<pk>[0-9]+)/comentario$', views.comentario_novo, name="comentario_novo"),

    url(r'^comenatario/(?P<pk>[0-9]+)/like$', views.comentario_like, name="comentario_like"),
    url(r'^comentario/(?P<pk>[0-9]+)/unlike$', views.comentario_unlike, name="comentario_unlike"),
]

projeto_blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include("blog.urls"))
]

blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Post(models.Model):
    titulo = models.CharField(max_length=200)
    texto = models.TextField()
    publicado = models.BooleanField(default=False)
    data_criado = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    autor = models.CharField(max_length=100)
    texto = models.TextField()
    unlikes = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    data_criado = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)


    def __str__(self):
        return self.autor + ' '+ str(id)

    def like(self):
        self.likes += 1

    def unlike(self):
        self.unlikes += 1

blog/forms.py
from django import forms

from blog.models import Comentario


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('autor', 'texto')

blog/views.py
# Create your views here.
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from blog.forms import ComentarioForm
from blog.models import Post, Comentario


class BlogIndex(ListView):
    queryset = Post.objects.all();
    template_name = 'home.html'
    paginate_by = 3

class BlogDetail(DetailView):
        model = Post
        template_name = 'post.html'

def comentario_novo(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.post = post
            comentario.save()
            return redirect (reverse ('post', kwargs={'pk': post.pk}))
    else:
        form = ComentarioForm()
    return render (request, 'comentario.html', {'form': form})

def comentario_like(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)
    comentario.like()
    comentario.save()
    return redirect(reverse ('post', kwargs={'pk': comentario.post_id}))

def comentario_unlike(reques, pk):
    comentario = get_object_or_404(Comentario, pk=pk)
    comentario.unlike()
    comentario.save()
    return redirect(reverse('post', kwargs={'pk': comentario.post_id}))

blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "icons/favicon.ico" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="Q Blog Feed" />
    <title>Blog Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/blog.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url "index" %}">Home</a>
          <a class="blog-nav-item" href="#">New features</a>
          <a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="#">New hires</a>
          <a class="blog-nav-item" href="#">About</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
          {% block post_entries %} {% endblock %}

          {% if is_paginated %}
            <ul class="pager">
              <li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>Prev</a></li>
              <li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Next</a></li>
            </ul>
    {% endif %}
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/docs.min.js" %}"></script>
  </body>
</html>

blog/templates/comentario.html
{% extends 'base.html' %}
{% block post_entries %}
        <form method="post" class="post-form"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Enviar</button>
    </form>
{% endblock %}

blog/templates/home.html
{% extends "base.html" %}

{% block post_entries %}

    {% for post in object_list %}
        <div class="post">
            <a href="{% url 'post' pk=post.pk %}">
                <h2> {{ post.titulo }}</h2>
            </a>
            <p class="meta">
                {{ post.data_criado }} | {{ post.autor }}
            </p>
            {{ post.texto }}
        </div>
    {% endfor %}

{% endblock %}

blog/templates/post.html
{% extends "base.html" %}

{% block post_entries %}

        <div class="post">
            <h2> {{ post.titulo }}</h2>
            <p class="meta">
                {{ post.data_criado }} | {{ post.autor }}
            </p>
            {{ post.texto }}
        </div>
         <a class="btn btn-default" href="{% url 'comentario_novo' pk=post.pk %}">Comentario novo</a>
        {%  for comentario in object.comentario_set.all %}
            <div class="comment">
                <div>{{ comentario.data_criado }} | {{ comentario.autor }}
                  ({{ comentario.likes }})  <a href="{% url 'comentario_like' pk=comentario.pk %}">Like</a> |
                  ({{ comentario.unlikes }})   <a href="{% url 'comentario_unlike' pk=comentario.pk %}">Disslike</a>
                </div>
                <p> {{ comentario.texto }}</p>
            </div>

        {% endfor %}

{% endblock %}